/*
 * SaaSus Billing API Schema
 * SaaSus Billing API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.billing.api;

import saasus.sdk.billing.ApiException;
import saasus.sdk.billing.models.Error;
import saasus.sdk.billing.models.StripeInfo;
import saasus.sdk.billing.models.UpdateStripeInfoParam;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StripeApi
 */
@Disabled
public class StripeApiTest {

    private final StripeApi api = new StripeApi();

    /**
     * Stripe連携情報を削除(Delete Stripe Connection)
     *
     * 請求業務で使う外部SaaSとの連携情報を削除します。  Delete connection with external billing SaaS 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteStripeInfoTest() throws ApiException {
        api.deleteStripeInfo();
        // TODO: test validations
    }

    /**
     * Stripe連携情報を取得(Get Stripe Connection information)
     *
     * 請求業務で使う外部SaaSとの連携情報を取得します。 現在は Stripe と連携が可能です。 連携を行わない場合は、 SaaSus SDK/API を利用して請求処理を実装する必要があります。  Get information on connnections with external billing SaaS. Currently possible to integrate with Stripe. Without integration, you will need to implement billing using the SaaSus SDK/API. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStripeInfoTest() throws ApiException {
        StripeInfo response = api.getStripeInfo();
        // TODO: test validations
    }

    /**
     * Stripe連携情報を更新(Update Stripe Connection Info)
     *
     * 請求業務で使う外部SaaSとの連携情報を更新します。 現在は Stripe と連携が可能です。  Updates information on connection with external billing SaaS. Currently possible to connect to Stripe. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateStripeInfoTest() throws ApiException {
        UpdateStripeInfoParam updateStripeInfoParam = null;
        api.updateStripeInfo(updateStripeInfoParam);
        // TODO: test validations
    }

}
