/*
 * SaaSus Auth API Schema
 * スキーマ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiKeys
 */
public class ApiKeysTest {
    private final ApiKeys model = new ApiKeys();

    /**
     * Model tests for ApiKeys
     */
    @Test
    public void testApiKeys() {
        // TODO: test ApiKeys
    }

    /**
     * Test the property 'apiKeys'
     */
    @Test
    public void apiKeysTest() {
        // TODO: test apiKeys
    }

}
