/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import saasus.sdk.auth.models.DnsRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BasicInfo
 */
public class BasicInfoTest {
    private final BasicInfo model = new BasicInfo();

    /**
     * Model tests for BasicInfo
     */
    @Test
    public void testBasicInfo() {
        // TODO: test BasicInfo
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'isDnsValidated'
     */
    @Test
    public void isDnsValidatedTest() {
        // TODO: test isDnsValidated
    }

    /**
     * Test the property 'certificateDnsRecord'
     */
    @Test
    public void certificateDnsRecordTest() {
        // TODO: test certificateDnsRecord
    }

    /**
     * Test the property 'cloudFrontDnsRecord'
     */
    @Test
    public void cloudFrontDnsRecordTest() {
        // TODO: test cloudFrontDnsRecord
    }

    /**
     * Test the property 'dkimDnsRecords'
     */
    @Test
    public void dkimDnsRecordsTest() {
        // TODO: test dkimDnsRecords
    }

    /**
     * Test the property 'defaultDomainName'
     */
    @Test
    public void defaultDomainNameTest() {
        // TODO: test defaultDomainName
    }

    /**
     * Test the property 'fromEmailAddress'
     */
    @Test
    public void fromEmailAddressTest() {
        // TODO: test fromEmailAddress
    }

    /**
     * Test the property 'replyEmailAddress'
     */
    @Test
    public void replyEmailAddressTest() {
        // TODO: test replyEmailAddress
    }

    /**
     * Test the property 'isSesSandboxGranted'
     */
    @Test
    public void isSesSandboxGrantedTest() {
        // TODO: test isSesSandboxGranted
    }

}
