/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomizePageSettingsProps
 */
public class CustomizePageSettingsPropsTest {
    private final CustomizePageSettingsProps model = new CustomizePageSettingsProps();

    /**
     * Model tests for CustomizePageSettingsProps
     */
    @Test
    public void testCustomizePageSettingsProps() {
        // TODO: test CustomizePageSettingsProps
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'termsOfServiceUrl'
     */
    @Test
    public void termsOfServiceUrlTest() {
        // TODO: test termsOfServiceUrl
    }

    /**
     * Test the property 'privacyPolicyUrl'
     */
    @Test
    public void privacyPolicyUrlTest() {
        // TODO: test privacyPolicyUrl
    }

    /**
     * Test the property 'googleTagManagerContainerId'
     */
    @Test
    public void googleTagManagerContainerIdTest() {
        // TODO: test googleTagManagerContainerId
    }

}
