/*
 * SaaSus Auth API Schema
 * スキーマ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import saasus.sdk.auth.models.Invitation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Invitations
 */
public class InvitationsTest {
    private final Invitations model = new Invitations();

    /**
     * Model tests for Invitations
     */
    @Test
    public void testInvitations() {
        // TODO: test Invitations
    }

    /**
     * Test the property 'invitations'
     */
    @Test
    public void invitationsTest() {
        // TODO: test invitations
    }

}
