/*
 * SaaSus Auth API Schema
 * スキーマ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SelfRegist
 */
public class SelfRegistTest {
    private final SelfRegist model = new SelfRegist();

    /**
     * Model tests for SelfRegist
     */
    @Test
    public void testSelfRegist() {
        // TODO: test SelfRegist
    }

    /**
     * Test the property 'enable'
     */
    @Test
    public void enableTest() {
        // TODO: test enable
    }

}
