/*
 * SaaSus Auth API Schema
 * スキーマ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SignUpWithAwsMarketplaceParam
 */
public class SignUpWithAwsMarketplaceParamTest {
    private final SignUpWithAwsMarketplaceParam model = new SignUpWithAwsMarketplaceParam();

    /**
     * Model tests for SignUpWithAwsMarketplaceParam
     */
    @Test
    public void testSignUpWithAwsMarketplaceParam() {
        // TODO: test SignUpWithAwsMarketplaceParam
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'registrationToken'
     */
    @Test
    public void registrationTokenTest() {
        // TODO: test registrationToken
    }

}
