/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SignInParam
 */
public class SignInParamTest {
    private final SignInParam model = new SignInParam();

    /**
     * Model tests for SignInParam
     */
    @Test
    public void testSignInParam() {
        // TODO: test SignInParam
    }

    /**
     * Test the property 'signInFlow'
     */
    @Test
    public void signInFlowTest() {
        // TODO: test signInFlow
    }

    /**
     * Test the property 'signInParameters'
     */
    @Test
    public void signInParametersTest() {
        // TODO: test signInParameters
    }

}
