/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SingleTenantSettings
 */
public class SingleTenantSettingsTest {
    private final SingleTenantSettings model = new SingleTenantSettings();

    /**
     * Model tests for SingleTenantSettings
     */
    @Test
    public void testSingleTenantSettings() {
        // TODO: test SingleTenantSettings
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'roleArn'
     */
    @Test
    public void roleArnTest() {
        // TODO: test roleArn
    }

    /**
     * Test the property 'cloudformationTemplateUrl'
     */
    @Test
    public void cloudformationTemplateUrlTest() {
        // TODO: test cloudformationTemplateUrl
    }

    /**
     * Test the property 'ddlTemplateUrl'
     */
    @Test
    public void ddlTemplateUrlTest() {
        // TODO: test ddlTemplateUrl
    }

    /**
     * Test the property 'roleExternalId'
     */
    @Test
    public void roleExternalIdTest() {
        // TODO: test roleExternalId
    }

}
