/*
 * SaaSus Smart API Gateway API Schema
 * SaaSus Smart API Gateway API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.apigateway.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import saasus.sdk.apigateway.models.EndpointSettings;
import saasus.sdk.apigateway.models.TenantRoutingType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateApiGatewaySettingsParam
 */
public class UpdateApiGatewaySettingsParamTest {
    private final UpdateApiGatewaySettingsParam model = new UpdateApiGatewaySettingsParam();

    /**
     * Model tests for UpdateApiGatewaySettingsParam
     */
    @Test
    public void testUpdateApiGatewaySettingsParam() {
        // TODO: test UpdateApiGatewaySettingsParam
    }

    /**
     * Test the property 'roleArn'
     */
    @Test
    public void roleArnTest() {
        // TODO: test roleArn
    }

    /**
     * Test the property 'roleExternalId'
     */
    @Test
    public void roleExternalIdTest() {
        // TODO: test roleExternalId
    }

    /**
     * Test the property 'internalEndpointHealthCheckPath'
     */
    @Test
    public void internalEndpointHealthCheckPathTest() {
        // TODO: test internalEndpointHealthCheckPath
    }

    /**
     * Test the property 'internalEndpointHealthCheckPort'
     */
    @Test
    public void internalEndpointHealthCheckPortTest() {
        // TODO: test internalEndpointHealthCheckPort
    }

    /**
     * Test the property 'internalEndpointHealthCheckProtocol'
     */
    @Test
    public void internalEndpointHealthCheckProtocolTest() {
        // TODO: test internalEndpointHealthCheckProtocol
    }

    /**
     * Test the property 'internalEndpointHealthStatusCodes'
     */
    @Test
    public void internalEndpointHealthStatusCodesTest() {
        // TODO: test internalEndpointHealthStatusCodes
    }

    /**
     * Test the property 'saasSubnetIds'
     */
    @Test
    public void saasSubnetIdsTest() {
        // TODO: test saasSubnetIds
    }

    /**
     * Test the property 'saasVpcId'
     */
    @Test
    public void saasVpcIdTest() {
        // TODO: test saasVpcId
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'saasAlbArn'
     */
    @Test
    public void saasAlbArnTest() {
        // TODO: test saasAlbArn
    }

    /**
     * Test the property 'endpointSettingsList'
     */
    @Test
    public void endpointSettingsListTest() {
        // TODO: test endpointSettingsList
    }

    /**
     * Test the property 'tenantRoutingType'
     */
    @Test
    public void tenantRoutingTypeTest() {
        // TODO: test tenantRoutingType
    }

}
