/*
 * SaaSus Communication API Schema
 * SaaSus Communication API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.communication.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import saasus.sdk.communication.models.Feedback;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Feedbacks
 */
public class FeedbacksTest {
    private final Feedbacks model = new Feedbacks();

    /**
     * Model tests for Feedbacks
     */
    @Test
    public void testFeedbacks() {
        // TODO: test Feedbacks
    }

    /**
     * Test the property 'feedbacks'
     */
    @Test
    public void feedbacksTest() {
        // TODO: test feedbacks
    }

}
