/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The status of whether a device is remembered. \&quot;remembered\&quot; enables device authentication, \&quot;not_remembered\&quot; disables it. 
 */
@JsonAdapter(DeviceRememberedStatus.Adapter.class)
public enum DeviceRememberedStatus {
  
  REMEMBERED("remembered"),
  
  NOT_REMEMBERED("not_remembered");

  private String value;

  DeviceRememberedStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DeviceRememberedStatus fromValue(String value) {
    for (DeviceRememberedStatus b : DeviceRememberedStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DeviceRememberedStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final DeviceRememberedStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DeviceRememberedStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DeviceRememberedStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DeviceRememberedStatus.fromValue(value);
  }
}

