/*
 * SaaSus Auth API Schema
 * Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.auth.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import saasus.sdk.auth.models.DeviceRememberedStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import saasus.sdk.auth.JSON;

/**
 * Parameters required to update a device status. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-06T12:17:01.545468350Z[Etc/UTC]")
public class UpdateDeviceStatusParam {
  public static final String SERIALIZED_NAME_ACCESS_TOKEN = "access_token";
  @SerializedName(SERIALIZED_NAME_ACCESS_TOKEN)
  private String accessToken;

  public static final String SERIALIZED_NAME_DEVICE_KEY = "device_key";
  @SerializedName(SERIALIZED_NAME_DEVICE_KEY)
  private String deviceKey;

  public static final String SERIALIZED_NAME_DEVICE_REMEMBERED_STATUS = "device_remembered_status";
  @SerializedName(SERIALIZED_NAME_DEVICE_REMEMBERED_STATUS)
  private DeviceRememberedStatus deviceRememberedStatus;

  public UpdateDeviceStatusParam() {
  }

  public UpdateDeviceStatusParam accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * A valid access token.
   * @return accessToken
  **/
  @javax.annotation.Nonnull
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }


  public UpdateDeviceStatusParam deviceKey(String deviceKey) {
    this.deviceKey = deviceKey;
    return this;
  }

   /**
   * The unique identifier of the device.
   * @return deviceKey
  **/
  @javax.annotation.Nonnull
  public String getDeviceKey() {
    return deviceKey;
  }

  public void setDeviceKey(String deviceKey) {
    this.deviceKey = deviceKey;
  }


  public UpdateDeviceStatusParam deviceRememberedStatus(DeviceRememberedStatus deviceRememberedStatus) {
    this.deviceRememberedStatus = deviceRememberedStatus;
    return this;
  }

   /**
   * Get deviceRememberedStatus
   * @return deviceRememberedStatus
  **/
  @javax.annotation.Nonnull
  public DeviceRememberedStatus getDeviceRememberedStatus() {
    return deviceRememberedStatus;
  }

  public void setDeviceRememberedStatus(DeviceRememberedStatus deviceRememberedStatus) {
    this.deviceRememberedStatus = deviceRememberedStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeviceStatusParam updateDeviceStatusParam = (UpdateDeviceStatusParam) o;
    return Objects.equals(this.accessToken, updateDeviceStatusParam.accessToken) &&
        Objects.equals(this.deviceKey, updateDeviceStatusParam.deviceKey) &&
        Objects.equals(this.deviceRememberedStatus, updateDeviceStatusParam.deviceRememberedStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, deviceKey, deviceRememberedStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeviceStatusParam {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    deviceKey: ").append(toIndentedString(deviceKey)).append("\n");
    sb.append("    deviceRememberedStatus: ").append(toIndentedString(deviceRememberedStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("access_token");
    openapiFields.add("device_key");
    openapiFields.add("device_remembered_status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("access_token");
    openapiRequiredFields.add("device_key");
    openapiRequiredFields.add("device_remembered_status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UpdateDeviceStatusParam
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateDeviceStatusParam.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateDeviceStatusParam is not found in the empty JSON string", UpdateDeviceStatusParam.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateDeviceStatusParam.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateDeviceStatusParam` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateDeviceStatusParam.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("access_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `access_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("access_token").toString()));
      }
      if (!jsonObj.get("device_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `device_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("device_key").toString()));
      }
      // validate the required field `device_remembered_status`
      DeviceRememberedStatus.validateJsonElement(jsonObj.get("device_remembered_status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateDeviceStatusParam.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateDeviceStatusParam' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateDeviceStatusParam> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateDeviceStatusParam.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateDeviceStatusParam>() {
           @Override
           public void write(JsonWriter out, UpdateDeviceStatusParam value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateDeviceStatusParam read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateDeviceStatusParam given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateDeviceStatusParam
  * @throws IOException if the JSON string is invalid with respect to UpdateDeviceStatusParam
  */
  public static UpdateDeviceStatusParam fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateDeviceStatusParam.class);
  }

 /**
  * Convert an instance of UpdateDeviceStatusParam to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

