/*
 * SaaSus Smart API Gateway API Schema
 * SaaSus Smart API Gateway API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package saasus.sdk.apigateway.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import saasus.sdk.apigateway.models.EndpointSettings;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import saasus.sdk.apigateway.JSON;

/**
 * DraftApiGatewaySettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-12T22:51:41.504076208Z[Etc/UTC]")
public class DraftApiGatewaySettings {
  public static final String SERIALIZED_NAME_INTERNAL_ENDPOINT_OPENAPI_DEFINITION_FILE_DOWNLOAD_URL = "internal_endpoint_openapi_definition_file_download_url";
  @SerializedName(SERIALIZED_NAME_INTERNAL_ENDPOINT_OPENAPI_DEFINITION_FILE_DOWNLOAD_URL)
  private String internalEndpointOpenapiDefinitionFileDownloadUrl;

  public static final String SERIALIZED_NAME_ENDPOINT_SETTINGS_LIST = "endpoint_settings_list";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_SETTINGS_LIST)
  private List<EndpointSettings> endpointSettingsList = new ArrayList<>();

  public DraftApiGatewaySettings() {
  }

  public DraftApiGatewaySettings internalEndpointOpenapiDefinitionFileDownloadUrl(String internalEndpointOpenapiDefinitionFileDownloadUrl) {
    this.internalEndpointOpenapiDefinitionFileDownloadUrl = internalEndpointOpenapiDefinitionFileDownloadUrl;
    return this;
  }

   /**
   * URL to download the auto-generated openapi definition file, which will be used to build the API Gateway.
   * @return internalEndpointOpenapiDefinitionFileDownloadUrl
  **/
  @javax.annotation.Nullable
  public String getInternalEndpointOpenapiDefinitionFileDownloadUrl() {
    return internalEndpointOpenapiDefinitionFileDownloadUrl;
  }

  public void setInternalEndpointOpenapiDefinitionFileDownloadUrl(String internalEndpointOpenapiDefinitionFileDownloadUrl) {
    this.internalEndpointOpenapiDefinitionFileDownloadUrl = internalEndpointOpenapiDefinitionFileDownloadUrl;
  }


  public DraftApiGatewaySettings endpointSettingsList(List<EndpointSettings> endpointSettingsList) {
    this.endpointSettingsList = endpointSettingsList;
    return this;
  }

  public DraftApiGatewaySettings addEndpointSettingsListItem(EndpointSettings endpointSettingsListItem) {
    if (this.endpointSettingsList == null) {
      this.endpointSettingsList = new ArrayList<>();
    }
    this.endpointSettingsList.add(endpointSettingsListItem);
    return this;
  }

   /**
   * Endpoint Settings List
   * @return endpointSettingsList
  **/
  @javax.annotation.Nonnull
  public List<EndpointSettings> getEndpointSettingsList() {
    return endpointSettingsList;
  }

  public void setEndpointSettingsList(List<EndpointSettings> endpointSettingsList) {
    this.endpointSettingsList = endpointSettingsList;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DraftApiGatewaySettings instance itself
   */
  public DraftApiGatewaySettings putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DraftApiGatewaySettings draftApiGatewaySettings = (DraftApiGatewaySettings) o;
    return Objects.equals(this.internalEndpointOpenapiDefinitionFileDownloadUrl, draftApiGatewaySettings.internalEndpointOpenapiDefinitionFileDownloadUrl) &&
        Objects.equals(this.endpointSettingsList, draftApiGatewaySettings.endpointSettingsList)&&
        Objects.equals(this.additionalProperties, draftApiGatewaySettings.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(internalEndpointOpenapiDefinitionFileDownloadUrl, endpointSettingsList, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DraftApiGatewaySettings {\n");
    sb.append("    internalEndpointOpenapiDefinitionFileDownloadUrl: ").append(toIndentedString(internalEndpointOpenapiDefinitionFileDownloadUrl)).append("\n");
    sb.append("    endpointSettingsList: ").append(toIndentedString(endpointSettingsList)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("internal_endpoint_openapi_definition_file_download_url");
    openapiFields.add("endpoint_settings_list");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("endpoint_settings_list");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DraftApiGatewaySettings
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DraftApiGatewaySettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DraftApiGatewaySettings is not found in the empty JSON string", DraftApiGatewaySettings.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DraftApiGatewaySettings.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("internal_endpoint_openapi_definition_file_download_url") != null && !jsonObj.get("internal_endpoint_openapi_definition_file_download_url").isJsonNull()) && !jsonObj.get("internal_endpoint_openapi_definition_file_download_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `internal_endpoint_openapi_definition_file_download_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("internal_endpoint_openapi_definition_file_download_url").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("endpoint_settings_list").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `endpoint_settings_list` to be an array in the JSON string but got `%s`", jsonObj.get("endpoint_settings_list").toString()));
      }

      JsonArray jsonArrayendpointSettingsList = jsonObj.getAsJsonArray("endpoint_settings_list");
      // validate the required field `endpoint_settings_list` (array)
      for (int i = 0; i < jsonArrayendpointSettingsList.size(); i++) {
        EndpointSettings.validateJsonElement(jsonArrayendpointSettingsList.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DraftApiGatewaySettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DraftApiGatewaySettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DraftApiGatewaySettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DraftApiGatewaySettings.class));

       return (TypeAdapter<T>) new TypeAdapter<DraftApiGatewaySettings>() {
           @Override
           public void write(JsonWriter out, DraftApiGatewaySettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DraftApiGatewaySettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             DraftApiGatewaySettings instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DraftApiGatewaySettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DraftApiGatewaySettings
  * @throws IOException if the JSON string is invalid with respect to DraftApiGatewaySettings
  */
  public static DraftApiGatewaySettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DraftApiGatewaySettings.class);
  }

 /**
  * Convert an instance of DraftApiGatewaySettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

