name: Test Publish Java SDK Snapshot to OSSRH

on:
  workflow_dispatch:
  push:
    branches:
      - feature/68

jobs:
  snapshot-deploy:
    name: Publish SNAPSHOT to OSSRH
    runs-on: ubuntu-latest

    steps:
      # Git リポジトリをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ★ setup-java の前に 1 ステップ追加
      - name: Write settings.xml manually
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
          <servers>
              <server>
              <id>central</id>
              <username>${{ secrets.OSSRH_USERNAME }}</username>
              <password>${{ secrets.OSSRH_PASSWORD }}</password>
              </server>
          </servers>
          </settings>
          EOF

      # Java + OSSRH 認証設定と GPG 鍵をセットアップ
      - name: Set up Java and Maven Settings
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          overwrite-settings: false 
          server-id: central
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # pom.xml のバージョンを `-SNAPSHOT` に変更
      - name: Bump version to SNAPSHOT
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          SNAPSHOT_VERSION="${VERSION%-SNAPSHOT}-SNAPSHOT"
          echo "Set version to $SNAPSHOT_VERSION"
          mvn versions:set -DnewVersion=$SNAPSHOT_VERSION -DgenerateBackupPoms=false

      # Sonatype Snapshots リポジトリに SNAPSHOT をデプロイ
      - name: Deploy SNAPSHOT to OSSRH
        run: mvn -B -ntp clean deploy