name: Test Publish Java SDK Snapshot to OSSRH

on:
  workflow_dispatch:
  push:
    branches:
      - feature/68

jobs:
  snapshot-deploy:
    name: Publish SNAPSHOT to OSSRH
    runs-on: ubuntu-latest

    steps:
      # Git リポジトリをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Java + OSSRH 認証設定と GPG 鍵をセットアップ
      - name: Set up Java and Maven Settings
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # pom.xml のバージョンを `-SNAPSHOT` に変更
      - name: Bump version to SNAPSHOT
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          SNAPSHOT_VERSION="${VERSION%-SNAPSHOT}-SNAPSHOT"
          echo "Set version to $SNAPSHOT_VERSION"
          mvn versions:set -DnewVersion=$SNAPSHOT_VERSION -DgenerateBackupPoms=false

      # Sonatype Snapshots リポジトリに SNAPSHOT をデプロイ
      - name: Deploy SNAPSHOT to OSSRH
        run: mvn deploy
        env:
            MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
